# @generated by `cargo buckal`

load("@buckal//:cargo_manifest.bzl", "cargo_manifest")
load("@buckal//:wrapper.bzl", "rust_library")

filegroup(
    name = "git-internal-vendor",
    srcs = glob(["**/**"]),
    out = "vendor",
)

cargo_manifest(
    name = "git-internal-manifest",
    vendor = ":git-internal-vendor",
)

rust_library(
    name = "git_internal",
    srcs = [":git-internal-vendor"],
    crate = "git_internal",
    crate_root = "vendor/src/lib.rs",
    edition = "2024",
    features = [
        "default",
        "diff_mydrs",
    ],
    rustc_flags = ["@$(location :git-internal-manifest[env_flags])"],
    visibility = ["PUBLIC"],
    deps = [
        "//third-party/rust/crates/ahash/0.8.12:ahash",
        "//third-party/rust/crates/async-trait/0.1.89:async-trait",
        "//third-party/rust/crates/axum/0.8.8:axum",
        "//third-party/rust/crates/bstr/1.12.1:bstr",
        "//third-party/rust/crates/byteorder/1.5.0:byteorder",
        "//third-party/rust/crates/bytes/1.11.1:bytes",
        "//third-party/rust/crates/chrono/0.4.44:chrono",
        "//third-party/rust/crates/colored/3.1.1:colored",
        "//third-party/rust/crates/crc32fast/1.5.0:crc32fast",
        "//third-party/rust/crates/dashmap/6.1.0:dashmap",
        "//third-party/rust/crates/diffs/0.5.1:diffs",
        "//third-party/rust/crates/encoding_rs/0.8.35:encoding_rs",
        "//third-party/rust/crates/flate2/1.1.9:flate2",
        "//third-party/rust/crates/futures-util/0.3.32:futures-util",
        "//third-party/rust/crates/futures/0.3.32:futures",
        "//third-party/rust/crates/hex/0.4.3:hex",
        "//third-party/rust/crates/libc/0.2.183:libc",
        "//third-party/rust/crates/lru-mem/0.3.0:lru-mem",
        "//third-party/rust/crates/memchr/2.8.0:memchr",
        "//third-party/rust/crates/natord/1.0.9:natord",
        "//third-party/rust/crates/num_cpus/1.17.0:num_cpus",
        "//third-party/rust/crates/path-absolutize/3.1.1:path-absolutize",
        "//third-party/rust/crates/rayon/1.11.0:rayon",
        "//third-party/rust/crates/ring/0.17.14:ring",
        "//third-party/rust/crates/rkyv/0.8.15:rkyv",
        "//third-party/rust/crates/sea-orm/1.1.19:sea-orm",
        "//third-party/rust/crates/serde/1.0.228:serde",
        "//third-party/rust/crates/serde_json/1.0.149:serde_json",
        "//third-party/rust/crates/sha1/0.10.6:sha1",
        "//third-party/rust/crates/sha2/0.10.9:sha2",
        "//third-party/rust/crates/similar/2.7.0:similar",
        "//third-party/rust/crates/tempfile/3.27.0:tempfile",
        "//third-party/rust/crates/thiserror/2.0.18:thiserror",
        "//third-party/rust/crates/threadpool/1.8.1:threadpool",
        "//third-party/rust/crates/tokio-stream/0.1.18:tokio-stream",
        "//third-party/rust/crates/tokio/1.50.0:tokio",
        "//third-party/rust/crates/tracing-subscriber/0.3.23:tracing-subscriber",
        "//third-party/rust/crates/tracing/0.1.44:tracing",
        "//third-party/rust/crates/uuid/1.22.0:uuid",
        "//third-party/rust/crates/zstd-sys/2.0.16+zstd.1.5.7:zstd-sys",
    ],
)
